development:
  adapter: postgresql
  encoding: unicode
  database: kill_or_cure_development
  min_messages: WARNING

test:
  adapter: postgresql
  encoding: unicode
  database: killorcure_test
  min_messages: WARNING
